model_name: "chatglm_pro"
api_type: "glm"
api_key: "b2xxxxxxxxxxxxxxxxxxxxxxxxxxx"
max_tries: 5
---
model_name: "gpt-3.5-turbo"
api_type: "openai"
api_key: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxx"
max_tries: 5